package pages.dashboard.products.supplier.crud;

import org.openqa.selenium.By;

class CRUDSupplierElement {
    By loc_lblSelectedLanguage = By.cssSelector(".language-selector .uik-select__valueWrapper");
    String languageLocator = "//*[@class = 'uik-select__label']/span[text()= '%s']";
    By loc_btnHeaderSave = By.cssSelector(".btn-save");
    By loc_btnHeaderDelete = By.cssSelector(".gs-button__red--outline");
    By loc_txtSupplierName = By.cssSelector("#name");
    By loc_txtSupplierCode = By.cssSelector("#code");
    By loc_txtPhoneNumber = By.cssSelector("#phone-number");
    By loc_txtEmail = By.cssSelector("#email");
    By loc_lblSelectedCountry = By.cssSelector("#countryCode");
    By loc_ddlCountry = By.cssSelector("#countryCode option");
    By loc_txtVNAddress = By.cssSelector("#address");
    By loc_lblSelectedVNCity = By.cssSelector("#province");
    By loc_ddlVNCity = By.cssSelector("#province option");
    By loc_lblSelectedVNDistrict = By.cssSelector("#district");
    By loc_ddlVNDistrict = By.cssSelector("#district option");
    By loc_lblSelectedVNWard = By.cssSelector("#ward");
    By loc_ddlVNWard = By.cssSelector("#ward option");
    By loc_txtNonVNStreetAddress = By.cssSelector("#address");
    By loc_txtNonVNAddress2 = By.cssSelector("#address2");
    By loc_txtNonVNCity = By.cssSelector("#cityName");
    By loc_lblSelectedNonVNProvince = By.cssSelector("#province");
    By loc_ddlNonVNProvince = By.cssSelector("#province option");
    By loc_txtNonVnZipcode = By.cssSelector("#zipCode");
    By loc_lblSelectedResponsibleStaff = By.cssSelector("#staff");
    By loc_ddlResponsibleStaff = By.cssSelector("#staff option");
    By loc_txtDescription = By.cssSelector("#description");
    By loc_txtSearchPurchaseOrder = By.cssSelector(".gs-search-box__wrapper .uik-input__input");
    By loc_tblSearchResult_purchaseOrderId = By.cssSelector(".gs-table-body-items .id");
    By loc_dlgConfirmDeleteSupplier = By.cssSelector(".modal-content");
    By loc_dlgConfirmDeleteSupplier_btnDelete = By.cssSelector(".gs-button__red");

    /* UI */
    By loc_lblBackToSupplierManagementPage = By.cssSelector("[class *=gss-content-header] a");
    By loc_lblPageTitle = By.cssSelector("[class *=gss-content-header] a +*");
    By loc_lblSave = By.cssSelector(".btn-save");
    By loc_lblCancel = By.cssSelector(".btn-cancel");
    By loc_lblDelete = By.cssSelector(".gs-button__red--outline");
    By loc_lblSupplierName = By.cssSelector("[for = name]");
    By loc_lblSupplierCode = By.cssSelector("[for = code]");
    By loc_lblPhoneNumber = By.cssSelector("[for = phone-number]");
    By loc_plhPhoneNumber = By.cssSelector("#phone-number");
    By loc_lblEmail = By.cssSelector("[for = email]");
    By loc_lblAddressInformation = By.cssSelector(".supplier-page__address h5");
    By loc_lblCountry = By.cssSelector("[for = countryCode]");
    By loc_lblVNAddress = By.xpath("//*[@id = 'address']/parent::div/parent::div/preceding-sibling::div");
    By loc_plhVNAddress = By.cssSelector("#address");
    By loc_lblVNCity = By.cssSelector("[for = province]");
    By loc_lblDefaultVNCity = By.cssSelector("#province option:nth-child(1)");
    By loc_lblVNDistrict = By.cssSelector("[for = district]");
    By loc_lblDefaultVNDistrict = By.cssSelector("#district option:nth-child(1)");
    By loc_lblVNWard = By.cssSelector("[for = ward]");
    By loc_lblDefaultVNWard = By.cssSelector("#ward option:nth-child(1)");
    By loc_lblNonVNAddress = By.xpath("//*[@id = 'address']/parent::div/parent::div/preceding-sibling::div");
    By loc_plhNonVNAddress = By.cssSelector("#address");
    By loc_lblNonVNAddress2 = By.cssSelector("[for = address2]");
    By loc_plhNonVNAddress2 = By.cssSelector("#address2");
    By loc_lblNonVNCity = By.cssSelector("[for = cityName]");
    By loc_plhNonVNCity = By.cssSelector("#cityName");
    By loc_lblNonVNState = By.cssSelector("[for = province]");
    By loc_lblDefaultNonVNState = By.cssSelector("#province option:nth-child(1)");
    By loc_lblNonVnZipcode = By.cssSelector("[for = zipCode]");
    By loc_plhNonVNZipcode = By.cssSelector("#zipCode");
    By loc_lblOtherInformation = By.cssSelector(".supplier-page__other-info h5");
    By loc_lblResponsibleStaff = By.cssSelector("[for = staff]");
    String loc_lblDefaultResponsibleStaff = "[value='%s']";
    By loc_lblDescription = By.xpath("//*[@id = 'staff']/parent::div/following-sibling::div[1]");
    By loc_lblOrderHistory = By.xpath("//*[contains(@class, 'uik-tab__item')][1]");
    By loc_plhSearchOrderHistory = By.cssSelector(".gs-search-box__wrapper .uik-input__input");
    By loc_tblOrderHistory = By.cssSelector(".gs-table-header-item");
    By loc_lblNoOrderHistory = By.cssSelector(".gs-table +* span");
    By loc_lblSupplierSummary = By.cssSelector(".suplier-page__supplier-status h5");
    By loc_lblSupplierStatus = By.cssSelector(".suplier-page__supplier-status .title-label");
    By loc_lblStatusOfSupplier = By.cssSelector(".suplier-page__supplier-status .label-status");
    By loc_dlgConfirmDeleteSupplierTitle = By.cssSelector(".modal-title");
    By loc_dlgConfirmDeleteSupplierContent = By.cssSelector(".modal-body");
    By loc_dlgConfirmDeleteSupplier_lblDelete = By.cssSelector(".gs-button__red");
    By loc_dlgConfirmDeleteSupplier_lblCancel = By.cssSelector(".modal-footer .gs-button__red--outline");
    By loc_lblSupplierNameError = By.cssSelector("#name +*");
    By lblSupplierCodeError = By.cssSelector("#code +*");
}
