package utilities.model.staffPermission;

import lombok.Data;

@Data
public class CreatePermission{
	private String customer_segment = "0";
	private String affiliate_resellerInventory = "0";
	private String analytics_orders = "0";
	private String product_productManagement = "0";
	private String affiliate_commission = "0";
	private String supplier_debt = "0";
	private String marketing_loyaltyPoint = "0";
	private String orders_orderList = "0";
	private String setting_tax = "0";
	private String setting_account = "0";
	private String setting_bankAccount = "0";
	private String affiliate_dropshipInformation = "0";
	private String shopee_none = "0";
	private String goChat_smsCampaign = "0";
	private String goChat_facebook = "0";
	private String affiliate_resellerPayout = "0";
	private String goChat_zalo = "0";
	private String home_none = "0";
	private String onlineStore_menu = "0";
	private String goWallet_none = "0";
	private String callCenter_none = "0";
	private String marketing_emailCampaign = "0";
	private String onlineStore_blog = "0";
	private String product_transfer = "0";
	private String marketing_loyaltyProgram = "0";
	private String service_serviceCollection = "0";
	private String setting_staffManagement = "0";
	private String affiliate_resellerOrders = "0";
	private String product_locationReceipt = "0";
	private String affiliate_resellerCustomer = "0";
	private String promotion_discountCode = "0";
	private String analytics_reservation = "0";
	private String onlineStore_domain = "0";
	private String cashbook_none = "0";
	private String reservation_reservationManagement = "0";
	private String setting_branchManagement = "0";
	private String marketing_buyLink = "0";
	private String promotion_discountCampaign = "0";
	private String orders_delivery = "0";
	private String orders_returnOrder = "0";
	private String product_inventory = "0";
	private String onlineStore_preferences = "0";
	private String setting_permission = "0";
	private String product_lotDate = "0";
	private String onlineStore_page = "0";
	private String product_location = "0";
	private String lazada_none = "0";
	private String setting_shippingAndPayment = "0";
	private String tiktok_none = "0";
	private String marketing_landingPage = "0";
	private String supplier_supplier = "0";
	private String onlineStore_theme = "0";
	private String affiliate_dropshipPayout = "0";
	private String promotion_flashSale = "0";
	private String customer_customerManagement = "0";
	private String marketing_pushNotification = "0";
	private String orders_quotation = "0";
	private String product_collection = "0";
	private String product_review = "0";
	private String orders_pos = "0";
	private String reservation_posService = "0";
	private String affiliate_dropshipOrders = "0";
	private String affiliate_resellerPartner = "0";
	private String supplier_purchaseOrder = "0";
	private String affiliate_resellerInformation = "0";
	private String affiliate_payoutHistory = "0";
	private String setting_storeInformation = "0";
	private String promotion_buyXGetY = "0";
	private String service_serviceManagement = "0";
	private String affiliate_dropshipPartner = "0";
	private String setting_storeLanguage = "0";
}