package utilities.model.staffPermission;

import lombok.Data;

@Data
public class CreatePermission{
	private String customer_segment = "0";
	private String affiliate_resellerInventory = "0";
	private String analytics_orders = "0";
	private String product_productManagement = "0";
	private String affiliate_commission = "0";
	private String supplier_debt = "0";
	private String marketing_loyaltyPoint = "0";
	private String orders_orderList = "0";
	private String setting_tax = "0";
	private String setting_account = "0";
	private String setting_bankAccount = "0";
	private String affiliate_dropshipInformation = "0";
	private String shopee_none = "0";
	private String goChat_smsCampaign = "0";
	private String goChat_facebook = "0";
	private String affiliate_resellerPayout = "0";
	private String goChat_zalo = "0";
	private String home_none = "0";
	private String onlineStore_menu = "0";
	private String goWallet_none = "0";
	private String callCenter_none = "0";
	private String marketing_emailCampaign = "0";
	private String onlineStore_blog = "0";
	private String product_transfer = "0";
	private String marketing_loyaltyProgram = "0";
	private String service_serviceCollection = "0";
	private String setting_staffManagement = "0";
	private String affiliate_resellerOrders = "0";
	private String product_locationReceipt = "0";
	private String affiliate_resellerCustomer = "0";
	private String promotion_discountCode = "0";
	private String analytics_reservation = "0";
	private String onlineStore_domain = "0";
	private String cashbook_none = "0";
	private String reservation_reservationManagement = "0";
	private String setting_branchManagement = "0";
	private String marketing_buyLink = "0";
	private String promotion_discountCampaign = "0";
	private String orders_delivery = "0";
	private String orders_returnOrder = "0";
	private String product_inventory = "0";
	private String onlineStore_preferences = "0";
	private String setting_permission = "0";
	private String product_lotDate = "0";
	private String onlineStore_page = "0";
	private String product_location = "0";
	private String lazada_none = "0";
	private String setting_shippingAndPayment = "0";
	private String tiktok_none = "0";
	private String marketing_landingPage = "0";
	private String supplier_supplier = "0";
	private String onlineStore_theme = "0";
	private String affiliate_dropshipPayout = "0";
	private String promotion_flashSale = "0";
	private String customer_customerManagement = "0";
	private String marketing_pushNotification = "0";
	private String orders_quotation = "0";
	private String product_collection = "0";
	private String product_review = "0";
	private String orders_pos = "0";
	private String reservation_posService = "0";
	private String affiliate_dropshipOrders = "0";
	private String affiliate_resellerPartner = "0";
	private String supplier_purchaseOrder = "0";
	private String affiliate_resellerInformation = "0";
	private String affiliate_payoutHistory = "0";
	private String setting_storeInformation = "0";
	private String promotion_buyXGetY = "0";
	private String service_serviceManagement = "0";
	private String affiliate_dropshipPartner = "0";
	private String setting_storeLanguage = "0";
	
	public static CreatePermission getFullPermissionModel() {
		
		String permissionBinary = "1".repeat(28);
		
        CreatePermission model = new CreatePermission();
        model.setCustomer_segment(permissionBinary);
        model.setAffiliate_resellerInventory(permissionBinary);
        model.setAnalytics_orders(permissionBinary);
        model.setProduct_productManagement(permissionBinary);
        model.setAffiliate_commission(permissionBinary);
        model.setSupplier_debt(permissionBinary);
        model.setMarketing_loyaltyPoint(permissionBinary);
        model.setOrders_orderList(permissionBinary);
        model.setSetting_tax(permissionBinary);
        model.setSetting_account(permissionBinary);
        model.setSetting_bankAccount(permissionBinary);
        model.setAffiliate_dropshipInformation(permissionBinary);
        model.setShopee_none(permissionBinary);
        model.setGoChat_smsCampaign(permissionBinary);
        model.setGoChat_facebook(permissionBinary);
        model.setAffiliate_resellerPayout(permissionBinary);
        model.setGoChat_zalo(permissionBinary);
        model.setHome_none(permissionBinary);
        model.setOnlineStore_menu(permissionBinary);
        model.setGoWallet_none(permissionBinary);
        model.setCallCenter_none(permissionBinary);
        model.setMarketing_emailCampaign(permissionBinary);
        model.setOnlineStore_blog(permissionBinary);
        model.setProduct_transfer(permissionBinary);
        model.setMarketing_loyaltyProgram(permissionBinary);
        model.setService_serviceCollection(permissionBinary);
        model.setSetting_staffManagement(permissionBinary);
        model.setAffiliate_resellerOrders(permissionBinary);
        model.setProduct_locationReceipt(permissionBinary);
        model.setAffiliate_resellerCustomer(permissionBinary);
        model.setPromotion_discountCode(permissionBinary);
        model.setAnalytics_reservation(permissionBinary);
        model.setOnlineStore_domain(permissionBinary);
        model.setCashbook_none(permissionBinary);
        model.setReservation_reservationManagement(permissionBinary);
        model.setSetting_branchManagement(permissionBinary);
        model.setMarketing_buyLink(permissionBinary);
        model.setPromotion_discountCampaign(permissionBinary);
        model.setOrders_delivery(permissionBinary);
        model.setOrders_returnOrder(permissionBinary);
        model.setProduct_inventory(permissionBinary);
        model.setOnlineStore_preferences(permissionBinary);
        model.setSetting_permission(permissionBinary);
        model.setProduct_lotDate(permissionBinary);
        model.setOnlineStore_page(permissionBinary);
        model.setProduct_location(permissionBinary);
        model.setLazada_none(permissionBinary);
        model.setSetting_shippingAndPayment(permissionBinary);
        model.setTiktok_none(permissionBinary);
        model.setMarketing_landingPage(permissionBinary);
        model.setSupplier_supplier(permissionBinary);
        model.setOnlineStore_theme(permissionBinary);
        model.setAffiliate_dropshipPayout(permissionBinary);
        model.setPromotion_flashSale(permissionBinary);
        model.setCustomer_customerManagement(permissionBinary);
        model.setMarketing_pushNotification(permissionBinary);
        model.setOrders_quotation(permissionBinary);
        model.setProduct_collection(permissionBinary);
        model.setProduct_review(permissionBinary);
        model.setOrders_pos(permissionBinary);
        model.setReservation_posService(permissionBinary);
        model.setAffiliate_dropshipOrders(permissionBinary);
        model.setAffiliate_resellerPartner(permissionBinary);
        model.setSupplier_purchaseOrder(permissionBinary);
        model.setAffiliate_resellerInformation(permissionBinary);
        model.setAffiliate_payoutHistory(permissionBinary);
        model.setSetting_storeInformation(permissionBinary);
        model.setPromotion_buyXGetY(permissionBinary);
        model.setService_serviceManagement(permissionBinary);
        model.setAffiliate_dropshipPartner(permissionBinary);
        model.setSetting_storeLanguage(permissionBinary);
        return model;
    }	
}