package web.Dashboard.products.productcollection.createeditproductcollection;

import org.openqa.selenium.By;

public class CreateProductCollectionElement {

    By loc_txtCollectionName = By.id("collectionName");
    By loc_txtUploadImage = By.cssSelector(".image-drop-zone input");
    By loc_chbManualValue = By.id("radio-collectionType-MANUAL");
    By loc_chbManualAction = By.xpath("//input[@id='radio-collectionType-MANUAL']/following-sibling::label");
    By loc_chbAutomatedValue = By.id("radio-collectionType-AUTOMATED");
    By loc_chbAutomatedAction = By.xpath("//input[@id='radio-collectionType-AUTOMATED']/following-sibling::label");
    By loc_chbAllConditionValue = By.id("radio-conditionType-ALL");
    By loc_chbAllConditionAction = By.xpath("//input[@id='radio-conditionType-ALL']/parent::div");
    By loc_chbAnyConditionValue = By.id("radio-conditionType-ANY");
    By loc_chbAnyConditionAction = By.xpath("//input[@id='radio-conditionType-ANY']/parent::div");
    By loc_lst_ddlCondition = By.id("conditionField");
    By loc_lst_ddlOperator = By.id("conditionOperand");
    By loc_lst_txtConditionValue = By.cssSelector(".uik-input__input");
    By loc_btnSelectProduct = By.cssSelector(".btn-addproduct");
    By loc_dlgSelectProduct_cbxSelectAllValue = By.xpath("//input[@name='check_all']");
    By loc_dlgSelectProduct_cbxSelectAllAction = By.xpath("//input[@name='check_all']//following-sibling::div");
    By loc_dlgSelectProduct_txtSearchForProduct = By.cssSelector(".search-input");
    By loc_dlgSelectProduct_btnOK = By.cssSelector(".footer-btn .gs-button__green");
    By loc_btnAddMoreCondition = By.cssSelector(".automated-config__header button > div");
    By loc_txtSEOTitle = By.id("seoTitle");
    By loc_txtSEODescription = By.id("seoDescription");
    By loc_txtSEOKeywords = By.id("seoKeywords");
    By loc_txtSEOUrl = By.id("seoUrl");
    By loc_btnClose = By.cssSelector(".modal-footer button");
    By loc_btnSave = By.cssSelector(".header-wrapper .gs-button__green");
    By loc_btnDelete = By.cssSelector(".icon-delete");
    By loc_btnEditTranslation = By.xpath("//*[contains(@class, 'btn-save')]/preceding-sibling::button");
    By loc_lst_txtPriority  = By.xpath("//td[contains(@class,'gs-table-body-item')]//input[@precision='0']");
    By loc_lst_lblProductName = By.xpath("//td[contains(@class,gs-table-body-item)][2]//b");
    By loc_icn_btnDelete = By.cssSelector(".btn-remove__row");
    By loc_lblCreateProductCollectionTitle = By.cssSelector(".gs-page-title");
    By loc_btnCancel = By.xpath("//div[contains(@class,'action-btn--group')]//button[2]");
    By loc_lblGeneralInformation = By.xpath("//button[@type='submit']//following-sibling::div[1]//h3");
    By loc_lblCollectionName = By.xpath("//label[@for='collectionName']");
    By loc_lblImages = By.xpath("//label[@for='collectionName']//following-sibling::label");
    By loc_lblDragAndDropPhoto = By.xpath("//input[@type='file']/following-sibling::div[2]");
    By loc_lblCollectionType = By.xpath("(//fieldset[@name='collectionType']/preceding::div//h3)[last()]");
    By loc_lblManualDescription = By.xpath("//div[@class='collection-description'][1]");
    By loc_lblAutomatedDescription = By.xpath("//div[@class='collection-description'][2]");
    By loc_lblFilterSortOption = By.xpath("//div[contains(@class,'collection-filter-and-sort')]//h3");
    By loc_lblFilterOption = By.xpath("//div[@class='filter-and-sort-text'][1]");
    By loc_lblSortOption = By.xpath("//div[@class='filter-and-sort-text'][2]");
    By loc_lblPriceRange = By.xpath("(//div[@class='filter-and-sort-checkbox-group'][1]//span)[1]");
    By loc_lblVariation = By.xpath("(//div[@class='filter-and-sort-checkbox-group'][1]//span)[2]");
    By loc_lblPromotion = By.xpath("(//div[@class='filter-and-sort-checkbox-group'][1]//span)[3]");
    By loc_lblUnit = By.xpath("(//div[@class='filter-and-sort-checkbox-group'][1]//span)[4]");
    By loc_lblBranch = By.xpath("(//div[@class='filter-and-sort-checkbox-group'][1]//span)[5]");
    By loc_lblPriceLowestToHighest = By.xpath("(//div[@class='filter-and-sort-checkbox-group'][2]//span)[1]");
    By loc_lblPriceHighestToLowest = By.xpath("(//div[@class='filter-and-sort-checkbox-group'][2]//span)[2]");
    By loc_lblNameAZ = By.xpath("(//div[@class='filter-and-sort-checkbox-group'][2]//span)[3]");
    By loc_lblNameZA = By.xpath("(//div[@class='filter-and-sort-checkbox-group'][2]//span)[4]");
    By loc_lblOldestToNewest = By.xpath("(//div[@class='filter-and-sort-checkbox-group'][2]//span)[5]");
    By loc_lblNewestToOldest = By.xpath("(//div[@class='filter-and-sort-checkbox-group'][2]//span)[6]");
    By loc_lblBestSelling = By.xpath("(//div[@class='filter-and-sort-checkbox-group'][2]//span)[7]");
    By loc_lblRatingLowestToHightest = By.xpath("(//div[@class='filter-and-sort-checkbox-group'][2]//span)[8]");
    By loc_lblRatingHighestToLowest = By.xpath("(//div[@class='filter-and-sort-checkbox-group'][2]//span)[9]");
    By loc_lblProductList = By.xpath("//div[@class='bnt-group_add_product']//preceding-sibling::h3");
    By loc_lblNoProduct = By.xpath("//div[@class='product-list__group']//span");
    By loc_lblSEOSetting = By.xpath("//div[contains(@class,' seo-editor')]//div[contains(@class,'gs-widget__header')]//h3");
    By loc_lblLivePreview = By.xpath("//span[@class='gs-fake-link ']//parent::div//preceding-sibling::div//span");
    By loc_tltLivePreview = By.xpath("//span[@class='gs-fake-link ']//parent::div//preceding-sibling::div//span/following-sibling::div//div");
    By loc_lblSEOTitle = By.xpath("//span[@class='gs-fake-link ']//parent::div/following-sibling::div[@class='mb-2'][1]/span");
    By loc_tltSEOTitle = By.xpath("//span[@class='gs-fake-link ']//parent::div/following-sibling::div[@class='mb-2'][1]//div/div");
    By loc_lblSEODescription = By.xpath("//span[@class='gs-fake-link ']//parent::div/following-sibling::div[@class='mb-2'][2]/span");
    By loc_tltSEODescription = By.xpath("//span[@class='gs-fake-link ']//parent::div/following-sibling::div[@class='mb-2'][2]//div/div");
    By loc_lblSEOKeywords = By.xpath("//span[@class='gs-fake-link ']//parent::div/following-sibling::div[@class='mb-2'][3]/span");
    By loc_tltSEOKeywords = By.xpath("//span[@class='gs-fake-link ']//parent::div/following-sibling::div[@class='mb-2'][3]//div/div");
    By loc_lblUrlLink =  By.xpath("//span[@class='gs-fake-link ']//parent::div/following-sibling::div[@class='mb-2'][4]/span");
    By loc_dlgSelectProduct_lblTitle = By.xpath("//h5[@class='modal-title']");
    By loc_dlgSelectProduct_lblProductNameCol = By.xpath("//div[@class='product-list-wrapper']//th[1]//div");
    By loc_dlgSelectProduct_lblUnitCol = By.xpath("//div[@class='product-list-wrapper']//th[2]");
    By loc_dlgSelectProduct_lblCostPriceCol = By.xpath("//div[@class='product-list-wrapper']//th[3]");
    By loc_dlgSelectProduct_lblListingPriceCol = By.xpath("//div[@class='product-list-wrapper']//th[4]");
    By loc_dlgSelectProduct_lblSellingPriceCol = By.xpath("//div[@class='product-list-wrapper']//th[5]");
    By loc_dlgSelectProduct_btnCancel = By.cssSelector(".footer-btn .gs-button__gray--outline");
    By loc_lblConditions = By.xpath("//div[@class='automated-config__header']//h3");
    By loc_lblProductMustMatch = By.xpath("//div[@class='automated-config__condition-type']/span[1]");
    By loc_dlgNotification = By.cssSelector(".modal-success");
    By loc_dlgNotification_btnClose = By.cssSelector("[data-testid='closeBtn']");
    By loc_dlgConfirmation = By.cssSelector(".confirm-modal");
    By loc_dlgConfirmation_btnOK = By.cssSelector(".confirm-modal .gs-button__green");
    By loc_dlgEditTranslation = By.cssSelector(".product-translate");
    By loc_dlgEditTranslation_btnSave = By.cssSelector(".modal.fade.show > .product-translate .gs-button__green");
    By loc_dlgToastSuccess = By.cssSelector(".Toastify__toast-body");
}
