package utilities.model.dashboard.orders.ordermanagement;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;
import utilities.model.dashboard.orders.orderdetail.PaymentHistoryInfo;

import java.util.List;

@JsonInclude(JsonInclude.Include.NON_DEFAULT)
@Data
public class OrderInManagement {
    private String id;
    private String productNames;
    private String bcOrderGroupId;
    private String channel;
    private int storeId;
    private String status;
    private String buyerName;
    private double total;
    private double subTotal;
    private String currency;
    private String paymentMethod;
    private String note;
    private String createdDate;
    private String createdBy;
    private String updatedDate;
    private int itemsCount;
    private String phone;
    private String displayName;
    private String email;
    private String userId;
    private String appInstall;
    private String location;
    private String orderType;
    private List<Item> items;
    private int customerId;
    private String customerFullName;
    private String customerCountry;
    private String customerAddress;
    private String customerAddress2;
    private String customerWard;
    private String customerDistrict;
    private String customerCity;
    private String city;
    private String customerState;
    private String customerZipCode;
    private String customerPhone;
    private String customerPhoneBackup;
    private String inStore;
    private int branchId;
    private String branchName;
    private String branchType;
    private String userName;
    private String wholesaleId;
    private String discountCode;
    private double discountAmount;
    private double shippingFee;
    private double feeDeduction;
    private double totalTaxAmount;
    private String shippingMethod;
    private String shippingService;
    private double totalCostPrice;
    private double debtAmount;
    private Boolean isPaid;
    private double receivedAmount;
    private String payType;
    private List<PaymentHistoryInfo> paymentHistories;
    private boolean hasDebt;
    private String rawPaymentMethod;
    private String fullShippingAddress;
    private String fullShippingAddressEn;
    private String partnerCode;
    private String phoneCode;
    private List<Object> orderTags;
    private String madeBy;
    private String statusUpdatedDate;
    private String approvedCommissionDate;
    private String customerSaleChannel;
    private int totalItems;
    private int totalItemQty;
    private String receiverDisplayName;
    private String receiverEmail;
    private String receiverPhone;
    private String receiverPhoneCode;
    private String creatorDisplayName;
    private String creatorEmail;
    private String creatorPhone;
    private String creatorPhoneCode;
    private double earningPoint;
    private double redeemPoint;
    private double pointAmount;
    private double exchangeAmount;
    private String discountType;
}
