package utilities.enums;

public enum DebtActionEnum {
	POS_DELIVERY_ORDER, 
	POS_NOW_ORDER, 
	RECEIPT_TO_CUSTOMER_DELETED, 
	RECEIPT_TO_CUSTOMER,
	GO_SOCIAL_ORDER,
	PAYMENT_TO_CUSTOMER,
	CONFIRM_PAYMENT_ORDER,
	DELIVERED_ORDER
}
