package utilities.enums;

public enum EventAction {
    GS_CHANGE_PRODUCT_STOCK,
    GS_SET_PRODUCT_STOCK,
    GS_TIKTOK_SYNC_ITEM_EVENT,
    GS_SHOPEE_SYNC_ITEM_EVENT,
    GS_LAZADA_SYNC_ITEM_EVENT,
    GS_SHOPEE_DOWNLOAD_PRODUCT,
    GS_TIKTOK_DOWNLOAD_PRODUCT,
    GS_LAZADA_DOWNLOAD_PRODUCT,
    GS_LAZADA_RECONNECT_ACCOUNT,
    GS_SHOPEE_RECONNECT_ACCOUNT,
    GS_TIKTOK_RECONNECT_ACCOUNT,
    GS_LAZADA_SYNC_ORDER,
    GS_SHOPEE_SYNC_ORDER,
    GS_TIKTOK_SYNC_ORDER,
    GS_LAZADA_ORVERIDE,
    GS_LAZADA_WEBHOOK_PRODUCT,
    GS_SHOPEE_WEBHOOK_PRODUCT,
    LZ_ORDER_STATUS_UPDATE,
    SP_ORDER_STATUS_PUSH,
    TT_ORDER_STATUS_UPDATE
}
