name: '[Android] Service detail'
on:
  workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to run tests'
          default: "STAG"
          type: choice
          options:
            - CA
            - STAG
            - PROD
            - PREPROD
        languageSF:
          description: 'Language on SSR to run tests'
          default: "VIE"
          type: choice
          options:
            - VIE
            - ENG
        languageDB:
          description: 'Language on Dashboard to run tests'
          default: "VIE"
          type: choice
          options:
            - VIE
            - ENG
       
jobs:
  automation:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v2
 
      - name: Replace env variables
        run: |
          cd GoSELL-Automation
          sed -i 's|environment=.*|environment=${{ inputs.environment }}|' src/main/resources/config.properties
          sed -i 's|languageSF=.*|languageSF=${{ inputs.languageSF }}|' src/main/resources/config.properties
          sed -i 's|languageDB=.*|languageDB=${{ inputs.languageDB }}|' src/main/resources/config.properties
          sed -i 's|headless=.*|headless=true|' src/main/resources/config.properties
          sed -i 's|enableProxy=.*|enableProxy=false|' src/main/resources/config.properties
          
      - name: Update STAG environment
        if: inputs.environment == 'STAG'
        run: 
            sed -i "s|udidAndroidVi=.*|udidAndroidVi=emulator-5554|" src/main/resources/environment/stag.properties
  
      - name: Update CA environment
        if: inputs.environment == 'CA'
        run: 
          sed -i "s|udidAndroidVi=.*|udidAndroidVi=emulator-5554|" src/main/resources/environment/ca.properties
      
      - name: Update PROD environment
        if: inputs.environment == 'PROD'
        run: 
          sed -i "s|udidAndroidVi=.*|udidAndroidVi=emulator-5554|" src/main/resources/environment/prod.properties
      
      - name: Update PREPROD environment
        if: inputs.environment == 'PREPROD'
        run: 
          sed -i "s|udidAndroidVi=.*|udidAndroidVi='emulator-5554'|" src/main/resources/environment/preprod.properties
          
         
      - name: Set up JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin'
          java-version: 22

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
  
      - name: Install Appium
        run: npm install -g appium > /dev/null 2>&1
  
      - name: Install UIAutomator2 driver
        run: appium driver install uiautomator2 > /dev/null 2>&1
  
      - name: Start Appium server
        run: nohup appium -a 0.0.0.0 -p 4723 -pa /wd/hub > appium_log.txt 2>&1 & > /dev/null 2>&1
  
      - name: Install dependencies
        run: |
          # mvn install -DskipTests > /dev/null 2>&1
          sudo apt update
          sudo apt install maven -y > /dev/null 2>&1
          mvn -version
      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_4
          script: mvn --batch-mode test "-DsuiteFile=test_config/android/buyer/BuyerServiceDetail.xml"
        
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Reports - Buyer Service Detail
          path: |
            **/html/index.html
            **/reportng.css
            **/reportng.js
            **/suite*_test*_results.html
            **/ExtentReport.html

