name: 'Run all'
on:  
  workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to run tests'
          default: "STAG"
          type: choice
          options:
            - CA
            - STAG
            - PROD
            - PREPROD
        languageSF:
          description: 'Language on SSR to run tests'
          default: "VIE"
          type: choice
          options:
            - VIE
            - ENG
        languageDB:
          description: 'Language on Dashboard to run tests'
          default: "VIE"
          type: choice
          options:
            - VIE
            - ENG
jobs:
  Run-on-web:
    strategy:
      fail-fast: false
      matrix:
        test_config_path:
          - test_config/web/BuyLinkTest.xml
          - test_config/web/createServiceTest.xml
          - test_config/web/productCollectionTest.xml
          - test_config/web/UserProfileSFTes.xml
          
    runs-on: ubuntu-latest
    steps:
     
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: 22

      - name: checkout
        uses: actions/checkout@v2

      - name: Replace env variables
        run: |
            sed -i 's|environment=.*|environment=${{ inputs.environment }}|' src/main/resources/config.properties
            sed -i 's|languageSF=.*|languageSF=${{ inputs.languageSF }}|' src/main/resources/config.properties
            sed -i 's|languageDB=.*|languageDB=${{ inputs.languageDB }}|' src/main/resources/config.properties
            sed -i 's|headless=.*|headless=true|' src/main/resources/config.properties
            sed -i 's|enableProxy=.*|enableProxy=false|' src/main/resources/config.properties
    
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-ubuntu
          restore-keys: |
            ${{ runner.os }}-maven-ubuntu
 
      - name: Install dependencies
        run:
          mvn install -DskipTests
 
      - name: Run tests
        run:
          mvn --batch-mode test "-DsuiteFile=${{ matrix.test_config_path }}"
          
      - name: Upload Test Report for web.
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Reports Web - $(basename "${{ matrix.test_config_path }}" .xml)
          path: |
            **/ExtentReport.html
 
          
  Run-on-android:
    strategy:
      fail-fast: false
      matrix:
        test_config_path:
          - test_config/android/buyer/BuyerMyProfile.xml
          - test_config/android/buyer/BuyerServiceDetail.xml
          - test_config/android/buyer/productCollectionTest.xml
    needs: Run-on-web
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: 22

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
  
      - name: Install Appium
        run: npm install -g appium > /dev/null 2>&1
  
      - name: Install UIAutomator2 driver
        run: appium driver install uiautomator2 > /dev/null 2>&1

      - name: Replace env variables
        run: |
          sed -i 's|environment=.*|environment=${{ inputs.environment }}|' src/main/resources/config.properties
          sed -i 's|languageSF=.*|languageSF=${{ inputs.languageSF }}|' src/main/resources/config.properties
          sed -i 's|languageDB=.*|languageDB=${{ inputs.languageDB }}|' src/main/resources/config.properties
          sed -i 's|headless=.*|headless=true|' src/main/resources/config.properties
          sed -i 's|enableProxy=.*|enableProxy=false|' src/main/resources/config.properties
          
      - name: Update STAG environment
        if: inputs.environment == 'STAG'
        run: 
          sed -i "s|udidAndroidVi=.*|udidAndroidVi=emulator-5554|" src/main/resources/environment/stag.properties
      
      - name: Update CA environment
        if: inputs.environment == 'CA'
        run: 
          sed -i "s|udidAndroidVi=.*|udidAndroidVi=emulator-5554|" src/main/resources/environment/ca.properties
      
      - name: Update PROD environment
        if: inputs.environment == 'PROD'
        run: 
          sed -i "s|udidAndroidVi=.*|udidAndroidVi=emulator-5554|" src/main/resources/environment/prod.properties
      
      - name: Update PREPROD environment
        if: inputs.environment == 'PREPROD'
        run: 
          sed -i "s|udidAndroidVi=.*|udidAndroidVi='emulator-5554'|" src/main/resources/environment/preprod.properties

      - name: Start Appium server
        run: nohup appium -a 0.0.0.0 -p 4723 -pa /wd/hub > appium_log.txt 2>&1 & > /dev/null 2>&1
  
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install maven -y > /dev/null 2>&1
          mvn -version
      
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_4_xl
          script: mvn --batch-mode test "-DsuiteFile=${{ matrix.test_config_path }}"
      
      - name: Upload Test Report for android.
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Reports - Android - $(basename "${{ matrix.test_config_path }}" .xml)
          path: |
            **/ExtentReport.html
            **/BufferLog.log
            **/appium_log.txt
            
      - name: Remove cloned repo
        run: |
            rm -r GoSELL-Automation
